### PR TITLE
Fix `api_group` attribute attribute of RBAC subjects.

### LINKED ISSUE #204: Unsupported value: "rbac.authorization.k8s.io": supported values: ""
Hi,
I'm running into this issue trying to bootstrap a k8s cluster using terraform

```
Terraform v0.11.10
+ provider.kubernetes v1.3.0
```
I want to apply the following role binding:

```
apiVersion: v1
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-role-binding
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: kube-system
```
I converted it into a terraform resource like this:
```hcl
resource "kubernetes_cluster_role_binding" "tiller" {
  metadata {
    name = "tiller-role-binding"
  }

  role_ref {
    kind = "ClusterRole"
    name = "cluster-admin"
    api_group = "rbac.authorization.k8s.io"
  }

  subject {
    kind = "ServiceAccount"
    name = "tiller"
    namespace = "kube-system"
  }
}
```
When I run terraform apply I get the following diff:

```
kubernetes_cluster_role_binding.tiller: Creating...
  metadata.#:                  "" => "1"
  metadata.0.generation:       "" => "<computed>"
  metadata.0.name:             "" => "tiller-role-binding"
  metadata.0.resource_version: "" => "<computed>"
  metadata.0.self_link:        "" => "<computed>"
  metadata.0.uid:              "" => "<computed>"
  role_ref.%:                  "" => "3"
  role_ref.api_group:          "" => "rbac.authorization.k8s.io"
  role_ref.kind:               "" => "ClusterRole"
  role_ref.name:               "" => "cluster-admin"
  subject.#:                   "" => "1"
  subject.0.api_group:         "" => "rbac.authorization.k8s.io"
  subject.0.kind:              "" => "ServiceAccount"
  subject.0.name:              "" => "tiller"
  subject.0.namespace:         "" => "kube-system"
```

Terraform adds `subject.0.api_group`.

If I apply the changes I get the following error:
```
1 error(s) occurred:

* kubernetes_cluster_role_binding.tiller: 1 error(s) occurred:

* kubernetes_cluster_role_binding.tiller: ClusterRoleBinding.rbac.authorization.k8s.io "tiller-role-binding" is invalid: subjects[0].apiGroup: Unsupported value: "rbac.authorization.k8s.io": supported values: ""
```

### PR DESCRIPTION
**Pull request by alexsomesan**
This change aligns the schemas of RBAC role binding resources better to the Kubernetes specification.
With this, the provider tries harder to avoid user configuration errors that result in cryptic errors from the Kubernetes API.

According to [Kubernetes docs](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#rolebinding-and-clusterrolebinding) the User and Group subject types belong to the `rbac.authorization.k8s.io`, so they need to be specified as such in subject entries. Unfortunately, Kubernetes silently "corrects" the value of `api_group` if an incorrect one is supplied, resulting in recurring Terraform diffs. Hence the change to make `api_group` computed in subjects.

On the the hand, in `role_ref` only `Role` and `ClusterRole` can be specified, both of which belong to the `rbac.authorization.k8s.io` API group. This being the only possible value is now reflected in validation.

There are three subject types possible in RBAC role bindings. This change also introduces acceptance tests to ensure all three subject types are supported as expected.

Fixes #204 #283

```
~/workspace/terraform-provider-kubernetes(fix-rbac) » TESTARGS="-run '^TestAccKubernetes(Cluster)?RoleBinding'" make testacc                                                                 alex@alexs-macbook
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run '^TestAccKubernetes(Cluster)?RoleBinding' -timeout 120m
?   	github.com/terraform-providers/terraform-provider-kubernetes	[no test files]
=== RUN   TestAccKubernetesClusterRoleBinding
--- PASS: TestAccKubernetesClusterRoleBinding (0.17s)
=== RUN   TestAccKubernetesClusterRoleBinding_serviceaccount_subject
--- PASS: TestAccKubernetesClusterRoleBinding_serviceaccount_subject (0.09s)
=== RUN   TestAccKubernetesClusterRoleBinding_group_subject
--- PASS: TestAccKubernetesClusterRoleBinding_group_subject (0.09s)
=== RUN   TestAccKubernetesClusterRoleBinding_importBasic
--- PASS: TestAccKubernetesClusterRoleBinding_importBasic (0.10s)
=== RUN   TestAccKubernetesRoleBinding_basic
--- PASS: TestAccKubernetesRoleBinding_basic (0.16s)
=== RUN   TestAccKubernetesRoleBinding_importBasic
--- PASS: TestAccKubernetesRoleBinding_importBasic (0.10s)
=== RUN   TestAccKubernetesRoleBinding_sa_subject
--- PASS: TestAccKubernetesRoleBinding_sa_subject (0.09s)
=== RUN   TestAccKubernetesRoleBinding_group_subject
--- PASS: TestAccKubernetesRoleBinding_group_subject (0.09s)
PASS
ok  	github.com/terraform-providers/terraform-provider-kubernetes/kubernetes	(cached)
------------------------------------------------------------
```

### CODE REVIEW

File: kubernetes/schema_rbac.go [hunk 1]
```diff
@@ -2,15 +2,17 @@ package kubernetes
...
 	return map[string]*schema.Schema{
 		"api_group": {
-			Type:        schema.TypeString,
-			Description: "The API group of the user. Always `rbac.authorization.k8s.io`",
-			Required:    true,
-			Default:     "rbac.authorization.k8s.io",
+			Type:         schema.TypeString,
+			Description:  "The API group of the user. Always `rbac.authorization.k8s.io`",
+			Required:     true,
+			Default:      "rbac.authorization.k8s.io",
```
Comment (paultyng) [inline kubernetes/schema_rbac.go]: I think you should just make this optional so the `Default` can apply.

Comment (alexsomesan) [reply kubernetes/schema_rbac.go]: I'd rather drop the default so people are aware of it. We're getting issues filed with examples that are wrong in that regard, so awareness of it is not what one would hope.
