### PR TITLE
r/kubernetes_pod: Add timeout to pod resource

### LINKED ISSUE #91: kubernetes_pod timeout
Hi there,

It would be nice if we can control the timeout in creation and especially destroy for some large images that takes to pull more than 5 minutes.

Error on create:
> kubernetes_pod.xxx: timeout while waiting for state to become 'Running' (last state: 'Pending', timeout: 5m0s)

error on destroy:
>kubernetes_pod.xxx: Still destroying... (ID: default/xxx-1, 1m0s elapsed)
>Error: Error applying plan:
>3 error(s) occurred:
>* kubernetes_pod.xxx (destroy): 1 error(s) occurred:
>* kubernetes_pod.xxx: Pod java-xxx-1 still exists (Pending)

### PR DESCRIPTION
**Pull request by appilon**
Fix #91 

Configurable timeouts for Create and Delete (plumbing was already in place). Let me know if we want to support more timeouts (read, update) or just address the ones described in the issue.

### CODE REVIEW

File: kubernetes/resource_kubernetes_pod.go [hunk 1]
```diff
@@ -24,6 +24,15 @@ func resourceKubernetesPod() *schema.Resource {
...
 			State: schema.ImportStatePassthrough,
 		},
+
+		Timeouts: &schema.ResourceTimeout{
+			Create:  schema.DefaultTimeout(5 * time.Minute),
+			Read:    schema.DefaultTimeout(5 * time.Minute),
+			Update:  schema.DefaultTimeout(5 * time.Minute),
+			Delete:  schema.DefaultTimeout(5 * time.Minute),
+			Default: schema.DefaultTimeout(5 * time.Minute),
+		},
```
Comment (catsby) [inline kubernetes/resource_kubernetes_pod.go]: These need to be referenced in the code that would use them. 

See:

- https://github.com/terraform-providers/terraform-provider-aws/blob/d5d8511e754406d10ecd108bb892e2f3296814d3/aws/resource_aws_db_instance.go#L528-L541

- https://github.com/terraform-providers/terraform-provider-aws/blob/d5d8511e754406d10ecd108bb892e2f3296814d3/aws/resource_aws_rds_cluster_instance.go#L474-L490

Comment (appilon) [reply kubernetes/resource_kubernetes_pod.go]: womp womp. Thank you for the links I was wondering how it worked.
