### PR TITLE
select default_secret for service account if there is more than one

### LINKED ISSUE #94: Unable to create service_account on OpenShift 3.7 due to 2 default secrets
### Terraform Version

0.11.0

### Affected Resource(s)

- kubernetes_service_account
- kubernetes_namespace

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.11.0"
}

variable "k8s_endpoint" {
  description = "k8s_endpoint"
}

variable "k8s_master_auth_client_certificate" {
  description = "k8s_master_auth_client_certificate"
}

variable "k8s_master_auth_client_key" {
  description = "k8s_master_auth_client_key"
}

variable "k8s_master_auth_cluster_ca_certificate" {
  description = "k8s_master_auth_cluster_ca_certificate"
}

provider "kubernetes" {
  host = "${var.k8s_endpoint}"
  client_certificate = "${base64decode(var.k8s_master_auth_client_certificate)}"
  client_key = "${base64decode(var.k8s_master_auth_client_key)}"
  cluster_ca_certificate = "${base64decode(var.k8s_master_auth_cluster_ca_certificate)}"
  load_config_file = false
}

resource "kubernetes_namespace" "dogs" {
  metadata {
    name = "dogs"
  }
}

resource "kubernetes_service_account" "dogs" {
  metadata {
    name = "dogs"
    namespace = "${kubernetes_namespace.dogs.metadata.0.name}"
  }
}
```

### Expected Behavior

The Kubernetes Provider should have created both a namespace and a service account in that namespace on OpenShift without errors. 

Note that the namespace and service account actually are created despite the error and show up in `terraform state list`.

### Actual Behavior

```
Rogers-MacBook-Pro:test-service-account roger$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + kubernetes_namespace.dogs
      id:                                               <computed>
      metadata.#:                                       "1"
      metadata.0.annotations.%:                         "3"
      metadata.0.annotations.openshift.io/description:  "Dogs"
      metadata.0.annotations.openshift.io/display-name: "Dogs"
      metadata.0.annotations.openshift.io/requester:    "admin"
      metadata.0.generation:                            <computed>
      metadata.0.name:                                  "dogs"
      metadata.0.resource_version:                      <computed>
      metadata.0.self_link:                             <computed>
      metadata.0.uid:                                   <computed>

  + kubernetes_service_account.dogs
      id:                                               <computed>
      default_secret_name:                              <computed>
      metadata.#:                                       "1"
      metadata.0.generation:                            <computed>
      metadata.0.name:                                  "dogs"
      metadata.0.namespace:                             "dogs"
      metadata.0.resource_version:                      <computed>
      metadata.0.self_link:                             <computed>
      metadata.0.uid:                                   <computed>


Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

kubernetes_namespace.dogs: Creating...
  metadata.#:                                       "" => "1"
  metadata.0.annotations.%:                         "" => "3"
  metadata.0.annotations.openshift.io/description:  "" => "Dogs"
  metadata.0.annotations.openshift.io/display-name: "" => "Dogs"
  metadata.0.annotations.openshift.io/requester:    "" => "admin"
  metadata.0.generation:                            "" => "<computed>"
  metadata.0.name:                                  "" => "dogs"
  metadata.0.resource_version:                      "" => "<computed>"
  metadata.0.self_link:                             "" => "<computed>"
  metadata.0.uid:                                   "" => "<computed>"
kubernetes_namespace.dogs: Creation complete after 0s (ID: dogs)
kubernetes_service_account.dogs: Creating...
  default_secret_name:         "" => "<computed>"
  metadata.#:                  "" => "1"
  metadata.0.generation:       "" => "<computed>"
  metadata.0.name:             "" => "dogs"
  metadata.0.namespace:        "" => "dogs"
  metadata.0.resource_version: "" => "<computed>"
  metadata.0.self_link:        "" => "<computed>"
  metadata.0.uid:              "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* kubernetes_service_account.dogs: 1 error(s) occurred:

* kubernetes_service_account.dogs: Expected 1 generated default secret, 2 found: [{  dogs-dockercfg-4fh66    } {  dogs-token-xfkg2    }]
```

Both the namespace (which in OpenShift is a project) and the service account were created despite the error!

The project and service account also both show up in Terraform state:

```
$ terraform state list
kubernetes_namespace.dogs
kubernetes_service_account.dogs

$ oc projects
You have access to the following projects and can switch between them with 'oc project <projectname>':

  * cats-and-dogs - Cats and Dogs
    default
    dogs
    kube-public
    kube-system
    logging
    management-infra
    openshift
    openshift-infra
    openshift-node

$ kubectl get sa dogs -o yaml
```
```yaml
apiVersion: v1
automountServiceAccountToken: false
imagePullSecrets:
- name: dogs-dockercfg-xlkd8
kind: ServiceAccount
metadata:
  creationTimestamp: 2017-12-02T19:59:30Z
  name: dogs
  namespace: dogs
  resourceVersion: "120113"
  selfLink: /api/v1/namespaces/dogs/serviceaccounts/dogs
  uid: 4ef2204f-d79b-11e7-817a-0277a1fe5d6e
secrets:
- name: dogs-token-lbsbv
- name: dogs-dockercfg-xlkd8
```

However, the project did not show up in the OpenShift Console until I ran `oadm policy add-role-to-user admin admin` after first selecting the new project with `oc project dogs`.

Note that the Terraform state does not have the default_secret_name attribute:

```
$ terraform state show kubernetes_service_account.dogs
id                          = dogs/dogs
metadata.#                  = 1
metadata.0.annotations.%    = 0
metadata.0.generate_name    = 
metadata.0.generation       = 0
metadata.0.labels.%         = 0
metadata.0.name             = dogs
metadata.0.namespace        = dogs
metadata.0.resource_version = 
metadata.0.self_link        = 
metadata.0.uid              = 
```

In contrast, when I created a service account with the Kubernetes Provider against Azure Container Service and Google Container Engine, the state in TFE did show an item like "default_secret_name": "cats-and-dogs-token-2f0b2". 

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The problem with OpenShift seems to be that a service account always has 2 secrets, one for service account authentication and one for Docker.  For example, here is the output from a service account I created with kubectl:

```
$ kubectl get sa cats-and-dogs -o yaml
```
```yaml
apiVersion: v1
imagePullSecrets:
- name: cats-and-dogs-dockercfg-56g9h
kind: ServiceAccount
metadata:
  creationTimestamp: 2017-12-02T16:30:00Z
  name: cats-and-dogs
  namespace: cats-and-dogs
  resourceVersion: "100176"
  selfLink: /api/v1/namespaces/cats-and-dogs/serviceaccounts/cats-and-dogs
  uid: 0a923ee9-d77e-11e7-817a-0277a1fe5d6e
secrets:
- name: cats-and-dogs-token-rwdxt
- name: cats-and-dogs-dockercfg-56g9h
```

The token/secret that I needed to use for authenticating against the Vault Kubernetes auth backend was the first.  I think the Kubernetes Provider is unable to decide which token to assign to the default_secret_name computed attribute.

### PR DESCRIPTION
**Pull request by pablo-ruth**
Proposal to fix #94 

If there is more than one secret created by default with a service account (ex: openshift), default to the first and override by a secret with "token" in the name if there is any.

### CODE REVIEW

File: kubernetes/resource_kubernetes_service_account.go [hunk 1]
```diff
@@ -104,11 +105,15 @@ func resourceKubernetesServiceAccountCreate(d *schema.ResourceData, meta interfa
 	})
 
 	diff := diffObjectReferences(svcAcc.Secrets, resp.Secrets)
+	defaultSecret := diff[0]
 	if len(diff) > 1 {
-		return fmt.Errorf("Expected 1 generated default secret, %d found: %s", len(diff), diff)
+		for _, secret := range diff {
+			if strings.Contains(secret.Name, "token") {
```
Comment (pdecat) [inline kubernetes/resource_kubernetes_service_account.go]: I believe this behavior should probably be traced in the logs at the `WARN` level and be documented on the resource page.

File: kubernetes/resource_kubernetes_service_account.go [hunk 2]
```diff
@@ -104,11 +105,15 @@ func resourceKubernetesServiceAccountCreate(d *schema.ResourceData, meta interfa
...
+				defaultSecret = secret
+			}
```
Comment (pdecat) [inline kubernetes/resource_kubernetes_service_account.go]: What about breaking out of the loop here?
```suggestion
				break
			}
```

File: website/docs/r/service_account.html.markdown [hunk 3]
```diff
@@ -76,4 +76,4 @@ The following arguments are supported:
 In addition to the arguments listed above, the following computed attributes are
 exported:
 
-* `default_secret_name` - Name of the default secret the is created & managed by the service
+* `default_secret_name` - Name of the default secret created & managed by the service. If there is more than one secret, the first with "token" in name is selected or, if none, the first in list.
```
Comment (pdecat) [inline website/docs/r/service_account.html.markdown]: To ensure the last part of that sentence, the assignment at https://github.com/terraform-providers/terraform-provider-kubernetes/pull/281/files#diff-375ac94c5bd4e304ddeb13226700ec77R112 needs to be moved out of the condition block.

Comment (pdecat) [reply website/docs/r/service_account.html.markdown]: Oops, missed https://github.com/terraform-providers/terraform-provider-kubernetes/pull/281/files#diff-375ac94c5bd4e304ddeb13226700ec77R108

It's ok then.

File: kubernetes/resource_kubernetes_service_account.go (hunk 1 above)
Comment (pablo-ruth) [reply kubernetes/resource_kubernetes_service_account.go]: Added

**Comment by pablo-ruth** [comment]
I changed matching string too, it's cleaner.

File: kubernetes/resource_kubernetes_service_account.go [hunk 4]
```diff
@@ -104,11 +105,17 @@ func resourceKubernetesServiceAccountCreate(d *schema.ResourceData, meta interfa
 	})
 
 	diff := diffObjectReferences(svcAcc.Secrets, resp.Secrets)
+	defaultSecret := diff[0]
 	if len(diff) > 1 {
-		return fmt.Errorf("Expected 1 generated default secret, %d found: %s", len(diff), diff)
+		for _, secret := range diff {
+			if strings.Contains(secret.Name, "-token-") {
```
Comment (alexsomesan) [inline kubernetes/resource_kubernetes_service_account.go]: This approach is problematic because there is no API contract to guarantee that token secrets must have the `-token-` string will be part of the name for token secrets.

There is however a `Type` attribute on `Secret` objects (see [here](https://github.com/kubernetes/api/blob/173ce66c1e39d1d0f56e0b3347ff2988068aecd0/core/v1/types.go#L4942)). You can filter the list of Secrets on this `Type` attribute for all objects with a value of `kubernetes.io/service-account-token` and that should give you a list of just the token type secrets. You'll most likely just get one during create, but I guess you can just pick the first one if you get more (very non-deterministic unfortunately).

Comment (pdecat) [reply kubernetes/resource_kubernetes_service_account.go]: Filtering on the secret type is indeed much cleaner!

Comment (pablo-ruth) [reply kubernetes/resource_kubernetes_service_account.go]: I added the filtering on secret type. I think we can keep the previous logic and return an error if we have more than one service account token. The filtering applies even if there is only one secret, I'm not sure if it's what you want... And we possibly can move this part in the "resource.Retry" block if we want to wait for a service account token to appear ?

Comment (pablo-ruth) [reply kubernetes/resource_kubernetes_service_account.go]: @alexsomesan ?

Comment (alexsomesan) [reply kubernetes/resource_kubernetes_service_account.go]: @pablo-ruth I think adding the `resource.Retry` around it is a good idea. 

However, I'm a bit concerned about doing `.Get(..)` calls for individual objects in a loop (the `for...range` around it) AND wrapping that in retries. It has the theoretical potential to cause a lot of requests in worst case conditions (and stress the API server unnecessarily).
The alternative would be to use a `.Secrets(namespace).List(..)` type of call OUTSIDE the loop and then filter it's results for the relevant secret name. We can that wrap that in a retry and not have it quadratically grow out of control.

What do you think? If you'd rather not add the retry, than I think we can merge like this.

Comment (alexsomesan) [reply kubernetes/resource_kubernetes_service_account.go]: Thanks!
