### PR TITLE
Refactor kubernetes client config initialization and fix in-cluster config

### LINKED ISSUE #679: Unauthorized after update to v1.10 using token auth
Hi there,
After upgrading to version 1.10, token authentication stopped working.

### Terraform Version
0.12.11

### Affected Resource(s)

- Seems to be a provider issue on version 1.10.0

### Terraform Configuration Files
```hcl
provider "kubernetes" {
  version = "1.10"
  cluster_ca_certificate = base64decode(
    data.google_container_cluster.this.master_auth[0].cluster_ca_certificate,
  )
  host             = data.google_container_cluster.this.endpoint
  token            = data.external.get_token.result["token"]
  load_config_file = false
}

data "google_container_cluster" "this" {
  name     = var.cluster_name
  location = var.cluster_location
  project  = var.project_id
}

data "external" "get_token" {
  program = ["/bin/bash", "${path.module}/get_token.sh"]
  query = {
    cluster_name     = data.google_container_cluster.this.name
    cluster_location = var.cluster_location
    project_id       = var.project_id
    credentials      = var.credentials
  }
}

resource "kubernetes_namespace" "this" {
  metadata {
    name = var.namespace
  }
}
```

### Expected Behavior
Get a success authentication.

### Actual Behavior
It fail, getting a "Unauthorized "

### Important Factoids
Using version 1.9 there is no problem

### PR DESCRIPTION
**Pull request by pdecat**
This PR is an alternative to #686 that intends to:
- cleanup client config initialization a bit,
- make sure cross-cluster works (resolve #679),
- make sure in-cluster config works without needing extra work like #497.

### CODE REVIEW

File: kubernetes/provider.go [hunk 1]
```diff
@@ -192,55 +191,100 @@ type KubeClientsets struct {
...
 			}
 		}
 	}
 
 	// Overriding with static configuration
-	cfg.UserAgent = fmt.Sprintf("HashiCorp/1.0 Terraform/%s", terraformVersion)
-
 	if v, ok := d.GetOk("host"); ok {
-		cfg.Host = v.(string)
+		overrides.ClusterInfo.Server = v.(string)
```
Comment (pdecat) [inline kubernetes/provider.go]: This change causes a regression when passing a bare IP address instead of a URL, e.g. when using this:
```
provider "kubernetes" {
  version = "1.10.1-dev3"

  load_config_file = false
  host             = data.google_container_cluster.cluster0.endpoint
  token            = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode(
    data.google_container_cluster.cluster0.master_auth[0].cluster_ca_certificate,
  )
}
```

I believe that's because `overrides.ClusterInfo.Server` always expects a URL: https://github.com/kubernetes/client-go/blob/v12.0.0/tools/clientcmd/api/types.go#L68-L69

While `cfg.Host` is most flexible: https://github.com/kubernetes/client-go/blob/v12.0.0/rest/config.go#L53-L57

Comment (pdecat) [reply kubernetes/provider.go]: A work-around is to use this:

```
  host             = "https://${data.google_container_cluster.cluster0.endpoint}:443"
```

But I'm experimenting how to avoid this.

Comment (pdecat) [reply kubernetes/provider.go]: Resolved.

Comment (pdecat) [reply kubernetes/provider.go]: Not the proper way to do it.

Comment (pdecat) [reply kubernetes/provider.go]: Alright, `overrides` are processed too late to be taken into account by `defaultServerUrlFor()`:

- https://github.com/kubernetes/client-go/blob/v12.0.0/tools/clientcmd/client_config.go#L176
- https://github.com/kubernetes/client-go/blob/v12.0.0/rest/config.go#L438-L439
- https://github.com/kubernetes/client-go/blob/v12.0.0/rest/url_utils.go#L85
- https://github.com/kubernetes/client-go/blob/v12.0.0/tools/clientcmd/client_config.go#L189
- https://github.com/kubernetes/client-go/blob/v12.0.0/tools/clientcmd/client_config.go#L211

**Comment by pdecat** [comment]
So far, I've tested this successfully in the following situations:

### A subset of acceptance tests

```
# make testacc TEST=./kubernetes TESTARGS='-run=TestAccKubernetesConfigMap -count=1'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./kubernetes -v -run=TestAccKubernetesConfigMap -count=1 -timeout 120m
go: finding k8s.io/client-go v12.0.0+incompatible
go: finding k8s.io/client-go v12.0.0+incompatible
go: finding github.com/terraform-providers/terraform-provider-google v2.17.0+incompatible
go: finding github.com/terraform-providers/terraform-provider-aws v2.32.0+incompatible
go: finding github.com/terraform-providers/terraform-provider-google v2.17.0+incompatible
go: finding github.com/terraform-providers/terraform-provider-aws v2.32.0+incompatible
=== RUN   TestAccKubernetesConfigMap_basic
--- PASS: TestAccKubernetesConfigMap_basic (1.38s)
=== RUN   TestAccKubernetesConfigMap_importBasic
--- PASS: TestAccKubernetesConfigMap_importBasic (0.57s)
=== RUN   TestAccKubernetesConfigMap_binaryData
--- PASS: TestAccKubernetesConfigMap_binaryData (0.79s)
=== RUN   TestAccKubernetesConfigMap_generatedName
--- PASS: TestAccKubernetesConfigMap_generatedName (0.49s)
=== RUN   TestAccKubernetesConfigMap_importGeneratedName
--- PASS: TestAccKubernetesConfigMap_importGeneratedName (0.57s)
PASS
ok      github.com/terraform-providers/terraform-provider-kubernetes/kubernetes 3.832s
```

### Using kubeconfig against GKE 1.13.11-gke.5

```
provider "kubernetes" {
  version = "1.10.1-dev6"

  config_path = var.gke_kubeconfig_gitlab-ci
}
```

### Using access token against GKE 1.13.11-gke.14

```
provider "kubernetes" {
  version = "1.10.1-dev6"

  load_config_file = false
  host             = data.google_container_cluster.cluster0.endpoint
  token            = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode(
    data.google_container_cluster.cluster0.master_auth[0].cluster_ca_certificate,
  )
}
```

### In-cluster with minikube and kubernetes 1.16

https://github.com/terraform-providers/terraform-provider-kubernetes/pull/690/files#diff-52766c12b9ab0b44de46fcc3af48a543R10-R17


### Cross-cluster with minikube and kubernetes 1.16 targeting minikube and kubernetes 1.15

https://github.com/terraform-providers/terraform-provider-kubernetes/pull/690/files#diff-2841352a525f3b955007a50733253d5bR11-R18

### Configurations not tested yet

- `username` / `password`
- `client_key`
- `exec`
- `insecure`
- mixes of all of the above and kubeconfig files

**Comment by alexsomesan** [comment]
I take this one for a ride in CI, three major cloud platforms.

**Comment by houqp** [comment]
@pdecat what's the state of this PR? Anything I could help to move it forward?

**Comment by pdecat** [comment]
At this stage, I believe it mostly needs more testing and a complete review.

**Comment by houqp** [comment]
@alexsomesan anything we could do to help move this forward?

**Comment by alexsomesan** [comment]
I've tested this and it works as specified. I'm a bit on the fence whether we should fail when running in-cluster unless the `load_config_file` is set, but the alternative of automatically picking in-cluster config would surely confuse a lot of inexperienced users. Overall I agree this is the right compromise.

On the other hand, I have one suggestion about the example based on a job. I think it should be more explicit about the fact that it's not illustrating the default in-cluster scenario and explain that external credentials are being injected as well as the external API being used. I have a feeling that in-cluster API is little known enough that this clarification will save confusion going forward.

**Comment by alexsomesan** [comment]
@houqp aiming to add this to the upcoming release. Likely on monday.

**Comment by pdecat** [comment]
> I've tested this and it works as specified.

Good news :tada: 

> I'm a bit on the fence whether we should fail when running in-cluster unless the `load_config_file` is set, but the alternative of automatically picking in-cluster config would surely confuse a lot of inexperienced users. Overall I agree this is the right compromise.

What about adding explicit messages with `INFO` or `WARN` log level during provider initialization to give users hints about where the configuration came from and why in-cluster config was not tried?

> On the other hand, I have one suggestion about the example based on a job. I think it should be more explicit about the fact that it's not illustrating the default in-cluster scenario and explain that external credentials are being injected as well as the external API being used. I have a feeling that in-cluster API is little known enough that this clarification will save confusion going forward.

We can indeed expand a bit on the [description of the job example](https://github.com/terraform-providers/terraform-provider-kubernetes/pull/690/files#diff-2e4f99ac46ed6eaa2c8d960354d9a94bR3).

Maybe referencing some other existing doc on the matter could help, e.g.:
- https://github.com/kubernetes/client-go/tree/master/examples/in-cluster-client-configuration
- https://kubernetes.io/docs/reference/access-authn-authz/authentication/#service-account-tokens

Feel free to add what you think is best, I'm not sure I'll have time to address this before Monday.

**Comment by alexsomesan** [comment]
Sounds good, @pdecat. I can take care of the changes.
I like the idea about exposing the config source with log messages.

**Comment by alexsomesan** [comment]
I've given it more thought and I think the examples included here all have their merits. I'd like to keep them as they are. I'll follow up with a simpler one for in-cluster in addition to this.
