### PR TITLE
Avoid crash when importing invalid ID

### LINKED ISSUE #41: Terraform import command crash failures for resources with ids of the form x/y
Hi @radeksimko ,

I am writing a resource where I need to compose the `id` of the resource from two other fields. I recalled `k8s` resource  does something like that for example - 

https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/kubernetes/structures.go#L15-L18

It just clicked me that calls like below would lead to a crash if some one would do -

`terraform import resource_kubernetes_config_map.mymap mapname`

like someone forgets that actual id is `namespace/mapname`
https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/kubernetes/resource_kubernetes_config_map.go#L79

It's all theory in my head at this point. But looks like we should return some meaningful error from the function which decomposes the id into sub-parts, probably something like
`func idParts(string) (string, string, error)`

### PR DESCRIPTION
**Pull request by radeksimko**
Fixes #41

### Before
```
$ terraform import kubernetes_pod.test terraform-nginx-example-43zkw
kubernetes_pod.test: Importing from ID "terraform-nginx-example-43zkw"...
kubernetes_pod.test: Import complete!
  Imported kubernetes_pod (ID: terraform-nginx-example-43zkw)
kubernetes_pod.test: Refreshing state... (ID: terraform-nginx-example-43zkw)
Error importing: 1 error(s) occurred:

* kubernetes_pod.test (import id: terraform-nginx-example-43zkw): 1 error(s) occurred:

* import kubernetes_pod.test result: terraform-nginx-example-43zkw: kubernetes_pod.test: unexpected EOF
panic: runtime error: index out of range
2017/08/11 15:02:10 [DEBUG] plugin: terraform-provider-kubernetes:
2017/08/11 15:02:10 [DEBUG] plugin: terraform-provider-kubernetes: goroutine 32 [running]:
2017/08/11 15:02:10 [DEBUG] plugin: terraform-provider-kubernetes: github.com/terraform-providers/terraform-provider-kubernetes/kubernetes.idParts(0xc4205d5b00, 0x1d, 0x68, 0x26d1000, 0xc4202a70f8, 0x0)
2017/08/11 15:02:10 [DEBUG] plugin: terraform-provider-kubernetes: 	/Users/radeksimko/gopath/src/github.com/terraform-providers/terraform-provider-kubernetes/kubernetes/structures.go:17 +0x95
...
```

### After
```
$ terraform import kubernetes_pod.test terraform-nginx-example-43zkw
kubernetes_pod.test: Importing from ID "terraform-nginx-example-43zkw"...
kubernetes_pod.test: Import complete!
  Imported kubernetes_pod (ID: terraform-nginx-example-43zkw)
kubernetes_pod.test: Refreshing state... (ID: terraform-nginx-example-43zkw)
Error importing: 1 error(s) occurred:

* kubernetes_pod.test (import id: terraform-nginx-example-43zkw): 1 error(s) occurred:

* import kubernetes_pod.test result: terraform-nginx-example-43zkw: kubernetes_pod.test: Unexpected ID format ("terraform-nginx-example-43zkw"), expected "namespace/name".
```

### CODE REVIEW

File: kubernetes/structures.go [hunk 1]
```diff
@@ -12,9 +12,14 @@ import (
 	api "k8s.io/kubernetes/pkg/api/v1"
 )
 
-func idParts(id string) (string, string) {
+func idParts(id string) (string, string, error) {
 	parts := strings.Split(id, "/")
-	return parts[0], parts[1]
+	if len(parts) < 2 {
```
Comment (tombuildsstuff) [inline kubernetes/structures.go]: does this want to be `if len(parts) != 2` to catch trailing slashes too?

Comment (radeksimko) [inline kubernetes/structures.go]: Good idea, I'll change it.
